---
- name: Install core packages for virtual machines
  hosts: ubuntu
  remote_user: root
  vars_files:
       - vars.yml
  become: false
  vars:
      ansible_ssh_private_key_file: "{{ key1 }}"


  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - python3-apt
        update_cache: true

